apiVersion: v1
kind: Service
metadata:
  name: avro
spec:
  selector:
    app: avro
  ports:
    - name: http
      protocol: TCP
      port: 8081
      targetPort: 8081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: avro
spec:
  selector:
    matchLabels:
      app: avro
  replicas: 1
  template:
    metadata:
      labels:
        app: avro
    spec:
      containers:
        - name: avro
          image: confluentinc/cp-schema-registry:7.1.1
          ports:
            - containerPort: 8081
          env:
            - name: SCHEMA_REGISTRY_HOST_NAME
              value: schema-registry
            - name: SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS
              value: kafka:29092
            - name: SCHEMA_REGISTRY_LISTENERS
              value: "http://0.0.0.0:8081"
            - name: SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL
              value: zookeeper:2181
